# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ashkan Hosseini
title: Senior Staff Software Engineer

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ashkanhosseini
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: ashkan-h
# xing_username: jekyll
# pinterest_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! My name is Ashkan and I'm a Senior Staff Software Engineer at Palo Alto Networks, working at the intersection of cybersecurity and machine learning.
  I received my M.S. from Columbia University in 2017, and my B.A. in computer science and mathematics from UC Berkeley in 2015. I love hacking, [modular synths](https://www.makenoisemusic.com/), and learning new things.
  I'm a movie buff, a [stream-of-consciousness](https://en.wikipedia.org/wiki/Virginia_Woolf) fan, and an avid runner. I can speak and write in Farsi, Arabic, and English.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Palo Alto Networks
        link: paloaltonetworks.com
        sub_title: Senior Staff Software Engineer
        caption: Jan 2020 - Present
        description: | # this will include new lines to allow paragraphs
            I'm part of the [Threat Prevention](https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/threat-prevention) team, where I build machine learning models and advanced heuristics to block malicious traffic on the wire.
            

      - layout: left
        title: Mandiant
        link: mandiant.com
        sub_title: Consultant
        caption: Feb 2010 - Dec 2019
        additional_links:
          - title: Link name
            icon: https://fontawesome.com/icons?d=gallery&s=brands&m=free
            url: https://google.com
        description: | # this will include new lines to allow paragraphs
            Executed web applications, Android and iOS applications, and network penetration tests. Performed both white box, source assisted code reviews, and black box security audits, and provided recommendations to address discovered security vulnerabilities.

      - layout: left
        title: Endgame
        link: endgame.com
        sub_title: Security Research Intern
        caption: Jun 2017 - Oct 2017
        comments: Acquired by Elastic in 2019
        description: | # this will include new lines to allow paragraphs
            Reverse engineered malware samples of different families to harden Endgame’s VMI sand- box platform against evasion techniques, and wrote signatures for Endgame’s internal sandbox to detect process injection and lateral movement.

      - layout: left
        title: MITRE
        link: mitre.org
        # link_text: boringcompany.com
        sub_title: Security Engineer Intern
        caption: May 2016 - Sep 2016
        description: | # this will include new lines to allow paragraphs
            Wired various program analysis and symbolic execution tools such as KLEE and JPF-SE into an automated build pipeline for vulnerability detection during compile-time.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Columbia University
        caption: 2016 - 2017
        sub_title: MS in Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at Columbia University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.

      - layout: left
        title: UC Berkeley
        caption: 2013 - 2015
        sub_title: BA in Computer Science and Math
        description: | # this will include new lines to allow paragraphs
          During my time at UC Berkeley I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.


  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 2020 Phishing Trends With PDF Files\
        Ashkan Hosseini, Ashutosh Chitwadgi\
        Unit 42 Palo Alto Networks 2021
      - Ten Process Injection Techniques: A Technical Survey Of Common And Trending Process Injection Techniques\
        Ashkan Hosseini
        Endgame Security 2017
      - Smart Locks: Lessons for Securing Commodity Internet of Things Devices\
        Grant Ho, Derek Leung, Pratyush Mishra, Ashkan Hosseini, David Wagner, and Dawn Song\
        ACM AsiaCCS 2016
      - Android Permissions Remystified: A Field Study on Contextual Integrity\
        Primal Wijesekera, University of British Columbia; Arjun Baokar, Ashkan Hosseini, Serge Egelman, and David Wagner\
        USENIX Security 2015

  - title: Media
    layout: text
    content: | # this will include new lines to allow paragraphs
      - TechRadar: [https://www.techradar.com/news/dont-open-that-pdf-email-attachment-it-could-well-be-malware]
      - CNN: [https://money.cnn.com/2017/07/12/technology/malware-researcher-helps-teen-hackers/index.html]

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      -

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
